version: "3.1"

services:
  apod-database:
    container_name: apod-database
    image: postgres:14.2-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  backend:
    container_name: apod-backend
    build: ../
    environment:
      SERVER_PORT: 4000
      DATABASE_URL: jdbc:postgresql://apod-database:5432/postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
    ports:
      - "4000:4000"


    depends_on:
      - apod-database